### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by leongersen** [leongersen/leongersen.github.io#1]
- [ ] Figure out how to deal with pretty urls, make sure content is not duplicated at `/topic`, `/topic/` and `/topic/index.html`
- [ ] Export the blog articles as HTML and upload here, remove at least the twitter includes
- [ ] Add static site generation to noUiSlider documentation
- [ ] Add readme explaining not to make doc PR's here
- [ ] Transfer domain to cloudflare
- [ ] Deal with GA
